# Generated by Django 4.1 on 2022-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_substitute',
            field=models.BooleanField(default=False),
        ),
    ]
