# Generated by Django 4.1.1 on 2022-09-08 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_player_time_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time_checked_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 20, 29, 46, 665570, tzinfo=datetime.timezone.utc)),
        ),
    ]
